"use client";

import Link from "next/link";
import { ArrowRight, BarChart3, ContactRound, Megaphone, PhoneCall, ShieldCheck, Workflow } from "lucide-react";
import { useTranslations } from "@/components/providers/i18n-provider";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { cn } from "@/lib/utils";

const features = [{ key: "campaigns", icon: Megaphone }, { key: "contacts", icon: ContactRound }, { key: "analytics", icon: BarChart3 }, { key: "security", icon: ShieldCheck }, { key: "automation", icon: Workflow }, { key: "calls", icon: PhoneCall }] as const;

export function HomePage() {
  const { t } = useTranslations();
  return <main><section className="page-container grid min-h-[calc(100vh-4rem)] items-center gap-12 py-20 lg:grid-cols-2"><div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{t("home.eyebrow")}</span><h1 className="mt-6 max-w-3xl text-4xl font-bold tracking-tight sm:text-6xl">{t("home.title")}</h1><p className="mt-6 max-w-2xl text-lg text-muted-foreground">{t("home.description")}</p><div className="mt-8 flex flex-wrap gap-3"><Link className={buttonVariants({ size: "lg" })} href="/register">{t("common.getStarted")}<ArrowRight className="size-4" /></Link><Link className={cn(buttonVariants({ variant: "outline", size: "lg" }))} href="/features">{t("common.learnMore")}</Link></div><div className="mt-10 grid max-w-xl grid-cols-3 gap-5 border-t pt-6">{["companies", "calls", "uptime"].map((item) => <div key={item}><p className="text-xl font-bold">{t(`home.stats.${item}.value`)}</p><p className="text-xs text-muted-foreground">{t(`home.stats.${item}.label`)}</p></div>)}</div></div><div className="relative"><div className="absolute -inset-8 -z-10 rounded-full bg-primary/10 blur-3xl" /><Card className="overflow-hidden shadow-soft"><div className="border-b p-5"><p className="font-semibold">{t("home.preview.title")}</p><p className="text-sm text-muted-foreground">{t("home.preview.description")}</p></div><CardContent className="grid gap-4 p-5 sm:grid-cols-2">{["campaigns", "contacts", "calls", "leads"].map((item) => <div className="rounded-lg border bg-muted/40 p-4" key={item}><p className="text-sm text-muted-foreground">{t(`home.preview.${item}`)}</p><p className="mt-2 text-2xl font-bold">{t(`home.preview.${item}Value`)}</p></div>)}</CardContent></Card></div></section><section className="border-y bg-muted/30 py-20"><div className="page-container"><div className="mx-auto max-w-2xl text-center"><h2 className="text-3xl font-bold">{t("home.featuresTitle")}</h2><p className="mt-3 text-muted-foreground">{t("home.featuresDescription")}</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(({ key, icon: Icon }) => <Card key={key}><CardContent className="p-6"><span className="inline-flex rounded-lg bg-primary/10 p-2 text-primary"><Icon className="size-5" /></span><h3 className="mt-4 font-semibold">{t(`features.${key}.title`)}</h3><p className="mt-2 text-sm text-muted-foreground">{t(`features.${key}.description`)}</p></CardContent></Card>)}</div></div></section></main>;
}
